language: objective-c
xcode_project: "Sugar.xcodeproj"
xcode_scheme: "Sugar Example"
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2
before_install: 
  - brew update
  - brew install carthage
  - carthage bootstrap --verbose
